#!/bin/bash
set -e

DIR=${1-swig/libbitcoin}
INC=${INC-"-Iswig -I/usr/include -I/usr/local/include"}
PERL=${PERL-perl}
SWIG=${SWIG-swig}

for file in $(find $DIR -name *.i)
do
    base=$(basename $file)
    swig_dir=$(dirname $file)
    cxx_dir=${swig_dir/#swig/src}; mkdir -p $cxx_dir
    perl_dir=${swig_dir/#swig/lib}; mkdir -p $perl_dir

    cxx_file=$cxx_dir/${base/%.i/_wrap.cxx}
    perl_file=$perl_dir/${base/%.i/.pm}

    echo '>' $SWIG $INC -c++ -perl -o $cxx_file -outdir $perl_dir $file
    $SWIG $INC -c++ -perl -o $cxx_file -outdir $perl_dir $file
done
